Refactor sudo usage in dotcube and dotcube-remote script

diff --git a/bin/dotcube b/bin/dotcube
--- a/bin/dotcube
+++ b/bin/dotcube
@@ -218,19 +218,34 @@ _task "Updating Ansible Galaxy"
 
 _task "Running playbook"; _task_done
 
+# Check if user can sudo without password
+# if sudo -n true 2>/dev/null; then
+#     echo "User can sudo without password"
+# else
+#     echo "User can't sudo or requires a password for sudo"
+#     exit 1
+# fi
 
 # Run playbook
 if [[ -f $VAULT_SECRET ]]; then
     if [[ -n "$DOTCUBE_REMOTE_TRIGGER" ]]; then
         ansible-playbook --vault-password-file "$VAULT_SECRET" "$DOTFILES_HOME/ansible/remote.yml" "$@"
     else
-        ansible-playbook --vault-password-file "$VAULT_SECRET" "$DOTFILES_HOME/ansible/main.yml" "$@"
+        if sudo -n true 2>/dev/null; then
+            ansible-playbook --vault-password-file "$VAULT_SECRET" "$DOTFILES_HOME/ansible/main.yml" "$@"
+        else
+            ansible-playbook --vault-password-file "$VAULT_SECRET" --ask-become-pass "$DOTFILES_HOME/ansible/main.yml" "$@"
+        fi
     fi
 else
     if [[ -n "$DOTCUBE_REMOTE_TRIGGER" ]]; then
         ansible-playbook "$DOTFILES_HOME/ansible/remote.yml" "$@"
     else
-        ansible-playbook "$DOTFILES_HOME/ansible/main.yml" "$@"
+        if sudo -n true 2>/dev/null; then
+            ansible-playbook "$DOTFILES_HOME/ansible/main.yml" "$@"
+        else
+            ansible-playbook --ask-become-pass "$DOTFILES_HOME/ansible/main.yml" "$@"
+        fi
     fi
 fi
 
